In [1]:
import numpy as np

In [2]:
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [3]:
type(data)

numpy.ndarray

In [4]:
# 차원 -> 이미지나 음성 데이터를 저장하는 구조
# 이미지 -> 가로 세로 2차원
# 동영상 -> 3차원
data1 = np.array([1,2,3,4,5])
data2 = np.array([[1,2,3], [4,5,6]])

In [5]:
data1.ndim, data2.ndim # 몇 차원인지

(1, 2)

In [7]:
data1.shape, data2.shape # 3개의 요소를 가진 리스트가 2개

((5,), (2, 3))

In [13]:
arr = np.array([1,2,3,4,5], dtype = "int")
arr.dtype

dtype('int32')

In [16]:
arr = arr.astype("float") # 본래 배열이 바뀌는 게 아님
arr.dtype 

dtype('float64')

In [18]:
# 행렬교환
arr = np.array([[1,2,3], [4,5,6]])
new_arr = arr.T
new_arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
arr = np.array([[1,2,3], [4,5,6]])
arr.shape # -> 3*2행렬
new_arr = arr.reshape((3,2))
new_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
arr = np.array([[1,2,3, 4,5,6]])
arr.shape # -> 3*2행렬
new_arr = arr.reshape((2,3))
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr = np.array([[1,2,3], [4,5,6]])
arr.resize((3,2))
arr # resize -> 원본이 바뀜, reshape -> 원본이 안바뀌고 바뀐배열을 반환

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
## 쉽게 만들기
arr =np.arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [41]:
arr = np.zeros((3,3))   #데이터가 정해져있을 때,(크기 고정되어 있을 때)
arr
arr = np.ones((3,3))
arr
arr = np.full((3,3), fill_value=5)
arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [42]:
np.random.rand(5)

array([0.84772969, 0.37766752, 0.34720638, 0.26805925, 0.78018225])

In [43]:
np.random.randn(5)

array([-1.58584644, -1.7433235 ,  0.21462968, -0.64923773, -0.17238813])

In [44]:
np.random.randint(3)

2

In [56]:
arr = np.arange(1,20,3)
arr_copy = arr.copy()
np.random.shuffle(arr_copy) # 본래의 배열이 섞임
arr_copy

array([ 7, 13,  1,  4, 10, 16, 19])

In [60]:
arr1 = ([1,2,3])
arr2 = ([4,5,6])
arr1 + arr2


[1, 2, 3, 4, 5, 6]